import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outRoot = join(__dirname, "../../book/online-book/src/public/figures");

const brand = {
  bg: "#0f1724",
  bg2: "#151e2d",
  panel: "#1b2637",
  panel2: "#22304a",
  mint: "#2cc9a8",
  mint2: "#8be4d3",
  navy: "#1a2744",
  text: "#e2ebf0",
  muted: "#9aaac4",
  yellow: "#f4d35e",
  orange: "#e8a545",
  danger: "#e85d75",
  line: "#39516c",
};

function esc(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function attrs(values) {
  return Object.entries(values)
    .filter(([, value]) => value !== undefined && value !== null && value !== false)
    .map(([key, value]) => `${key}="${esc(value)}"`)
    .join(" ");
}

function text(x, y, value, options = {}) {
  const { className = "label", anchor = "middle", size, color, weight, lineHeight = 20 } = options;
  const lines = String(value).split("\n");
  const baseAttrs = attrs({
    x,
    y,
    "text-anchor": anchor,
    class: className,
    "font-size": size,
    fill: color,
    "font-weight": weight,
  });
  if (lines.length === 1) return `<text ${baseAttrs}>${esc(value)}</text>`;
  return `<text ${baseAttrs}>${lines
    .map((line, index) => {
      const dy = index === 0 ? 0 : lineHeight;
      return `<tspan x="${x}" dy="${dy}">${esc(line)}</tspan>`;
    })
    .join("")}</text>`;
}

function box(x, y, width, height, label, options = {}) {
  const {
    className = "box",
    titleClass = "box-label",
    sub,
    accent = false,
    muted = false,
    dashed = false,
  } = options;
  const classes = [className, accent && "accent", muted && "muted", dashed && "dashed"]
    .filter(Boolean)
    .join(" ");
  const labelY = y + height / 2 + (sub ? -6 : 6);
  return `<g>
  <rect ${attrs({ x, y, width, height, rx: 8, ry: 8, class: classes })}/>
  ${text(x + width / 2, labelY, label, { className: titleClass })}
  ${sub ? text(x + width / 2, y + height / 2 + 20, sub, { className: "sub-label", lineHeight: 16 }) : ""}
</g>`;
}

function lane(x, y, width, height, label) {
  return `<g>
  <rect ${attrs({ x, y, width, height, rx: 8, ry: 8, class: "lane" })}/>
  ${text(x + 24, y + 34, label, { className: "lane-label", anchor: "start" })}
</g>`;
}

function arrow(x1, y1, x2, y2, options = {}) {
  const { label, dashed = false, color = brand.mint, bend } = options;
  const classes = ["arrow", dashed && "dashed"].filter(Boolean).join(" ");
  const shape = bend
    ? `<path ${attrs({ d: `M ${x1} ${y1} C ${bend[0]} ${bend[1]}, ${bend[2]} ${bend[3]}, ${x2} ${y2}`, class: classes, stroke: color })}/>`
    : `<line ${attrs({ x1, y1, x2, y2, class: classes, stroke: color })}/>`;
  const labelSvg = label
    ? text((x1 + x2) / 2, (y1 + y2) / 2 - 10, label, { className: "edge-label" })
    : "";
  return `${shape}${labelSvg}`;
}

function pill(x, y, width, height, label, options = {}) {
  return `<g>
  <rect ${attrs({ x, y, width, height, rx: height / 2, ry: height / 2, class: options.accent ? "pill accent" : "pill" })}/>
  ${text(x + width / 2, y + height / 2 + 6, label, { className: "pill-label" })}
</g>`;
}

function codeChip(x, y, label, width = 180) {
  return `<g>
  <rect ${attrs({ x, y, width, height: 36, rx: 6, ry: 6, class: "code-chip" })}/>
  ${text(x + width / 2, y + 23, label, { className: "code-label" })}
</g>`;
}

function diagram({ width, height, title, subtitle, body }) {
  return `<!-- Generated by tools/book-figures/generate.mjs. Do not edit directly. -->
<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="title desc">
  <title id="title">${esc(title)}</title>
  <desc id="desc">${esc(subtitle || title)}</desc>
  <defs>
    <linearGradient id="bg" x1="0" x2="1" y1="0" y2="1">
      <stop offset="0" stop-color="${brand.bg}"/>
      <stop offset="1" stop-color="#0d121b"/>
    </linearGradient>
    <linearGradient id="mintFill" x1="0" x2="1" y1="0" y2="1">
      <stop offset="0" stop-color="${brand.mint}" stop-opacity="0.28"/>
      <stop offset="1" stop-color="${brand.mint2}" stop-opacity="0.12"/>
    </linearGradient>
    <marker id="arrowHead" markerWidth="10" markerHeight="10" refX="8" refY="5" orient="auto">
      <path d="M 0 0 L 10 5 L 0 10 z" fill="${brand.mint}"/>
    </marker>
  </defs>
  <style>
    text { font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
    .canvas { fill: url(#bg); }
    .title { fill: ${brand.text}; font-size: 24px; font-weight: 750; }
    .subtitle { fill: ${brand.muted}; font-size: 13px; }
    .lane { fill: ${brand.bg2}; stroke: ${brand.line}; stroke-width: 1.4; rx: 8; ry: 8; }
    .lane-label { fill: ${brand.mint2}; font-size: 18px; font-weight: 700; }
    .box { fill: ${brand.panel}; stroke: ${brand.line}; stroke-width: 1.4; rx: 8; ry: 8; }
    .box.accent { fill: url(#mintFill); stroke: ${brand.mint}; stroke-width: 1.8; }
    .box.muted { fill: #121a29; stroke: #2a3a50; }
    .box.dashed { stroke-dasharray: 7 6; }
    .box-label { fill: ${brand.text}; font-size: 16px; font-weight: 700; }
    .sub-label { fill: ${brand.muted}; font-size: 12px; font-weight: 520; }
    .label { fill: ${brand.text}; font-size: 15px; font-weight: 640; }
    .muted-label { fill: ${brand.muted}; font-size: 13px; font-weight: 520; }
    .edge-label { fill: ${brand.mint2}; font-size: 12px; font-weight: 720; }
    .arrow { fill: none; stroke-width: 2.2; marker-end: url(#arrowHead); stroke-linecap: round; }
    .arrow.dashed { stroke-dasharray: 7 6; }
    .pill { fill: #121a29; stroke: ${brand.line}; stroke-width: 1.4; }
    .pill.accent { fill: #163c42; stroke: ${brand.mint}; }
    .pill-label { fill: ${brand.text}; font-size: 14px; font-weight: 720; }
    .code-chip { fill: #0a0f14; stroke: #2a3a50; stroke-width: 1.2; }
    .code-label { fill: ${brand.yellow}; font-size: 13px; font-family: "SFMono-Regular", Consolas, ui-monospace, monospace; font-weight: 650; }
    .small { fill: ${brand.muted}; font-size: 12px; font-weight: 600; }
    .warn { fill: ${brand.orange}; font-size: 13px; font-weight: 750; }
    @media (prefers-reduced-motion: no-preference) {
      .box.accent, .pill.accent {
        animation: softPulse 6s ease-in-out infinite;
      }
      .arrow:not(.dashed) {
        stroke-dasharray: 12 12;
        animation: arrowFlow 14s linear infinite;
      }
    }
    @keyframes softPulse {
      0%, 100% { filter: drop-shadow(0 0 0 rgba(44, 201, 168, 0)); }
      50% { filter: drop-shadow(0 0 8px rgba(44, 201, 168, 0.28)); }
    }
    @keyframes arrowFlow {
      from { stroke-dashoffset: 0; }
      to { stroke-dashoffset: -120; }
    }
  </style>
  <rect class="canvas" x="0" y="0" width="${width}" height="${height}" rx="8"/>
  ${text(32, 42, title, { className: "title", anchor: "start" })}
  ${subtitle ? text(32, 66, subtitle, { className: "subtitle", anchor: "start" }) : ""}
  ${body}
</svg>
`;
}

function keyedChildrenDiagram({ title, subtitle, oldItems, newItems, links, notes = [] }) {
  const maxItems = Math.max(oldItems.length, newItems.length);
  const notesY = 126 + maxItems * 58 + 34;
  const height = notes.length > 0 ? notesY + notes.length * 22 + 38 : 450;
  const row = (x, y, label, items, highlightIndex) => {
    const cells = items
      .map((item, index) => {
        const cls = index === highlightIndex ? "box accent" : "box";
        return `<rect ${attrs({ x, y: y + index * 58, width: 120, height: 42, rx: 8, ry: 8, class: cls })}/>
${text(x + 60, y + index * 58 + 27, item, { className: "box-label" })}`;
      })
      .join("\n");
    return `${text(x + 60, y - 18, label, { className: "lane-label" })}${cells}`;
  };
  const arrows = links
    .map(([from, to, label, dashed]) =>
      arrow(258, 150 + from * 58, 452, 150 + to * 58, {
        label,
        dashed,
        color: dashed ? brand.orange : brand.mint,
        bend: [320, 150 + from * 58, 390, 150 + to * 58],
      }),
    )
    .join("\n");
  return diagram({
    width: 720,
    height,
    title,
    subtitle,
    body: `
${row(138, 126, "c1: old children", oldItems)}
${row(462, 126, "c2: new children", newItems)}
${arrows}
${notes
  .map((note, index) =>
    text(360, notesY + index * 22, note, { className: index === 0 ? "warn" : "muted-label" }),
  )
  .join("\n")}
`,
  });
}

const diagrams = [
  {
    path: "00-introduction/what-is-vue/vue-implementation-map.svg",
    svg: () =>
      diagram({
        width: 980,
        height: 500,
        title: "Vue.js as an implementation map",
        subtitle:
          "The book follows the path from declarative UI to the runtime and compiler pieces behind it.",
        body: `
${box(52, 130, 190, 78, "Declarative UI", { sub: "template / render" })}
${box(286, 130, 180, 78, "Component", { sub: "state + view" })}
${box(510, 130, 180, 78, "Virtual DOM", { sub: "VNode tree" })}
${box(734, 130, 190, 78, "Renderer", { sub: "patch DOM" })}
${arrow(242, 169, 286, 169)}
${arrow(466, 169, 510, 169)}
${arrow(690, 169, 734, 169)}
${box(172, 292, 216, 72, "Reactivity", { sub: "track -> trigger", accent: true })}
${box(592, 292, 216, 72, "Template Compiler", { sub: "template -> render", accent: true })}
${arrow(280, 292, 370, 208, { label: "updates" })}
${arrow(700, 292, 600, 208, { label: "creates" })}
${pill(414, 398, 152, 42, "chibivue")}
${arrow(490, 398, 490, 230, { label: "build in layers", dashed: true })}
`,
      }),
  },
  {
    path: "00-introduction/vue-core-components/package-dependency-overview.svg",
    svg: () =>
      diagram({
        width: 1100,
        height: 660,
        title: "Vue package dependency map",
        subtitle:
          "Compiler packages prepare render functions; runtime packages mount and update the app.",
        body: `
${lane(70, 110, 960, 250, "Compiler packages")}
${lane(70, 410, 960, 152, "Runtime packages")}
${box(128, 214, 214, 72, "@vue/compiler-sfc", { sub: "SFC compiler", accent: true })}
${box(440, 156, 214, 72, "@vue/compiler-dom", { sub: "DOM compiler" })}
${box(440, 278, 214, 72, "@vue/compiler-core", { sub: "shared compiler" })}
${box(792, 260, 150, 72, "vue", { sub: "public package", accent: true })}
${box(320, 452, 204, 64, "@vue/runtime-dom", { sub: "browser runtime" })}
${box(608, 452, 204, 64, "@vue/runtime-core", { sub: "renderer core" })}
${box(876, 452, 120, 64, "@vue/reactivity", { sub: "effects" })}
${arrow(342, 242, 440, 192, { label: "uses" })}
${arrow(342, 258, 440, 314, { label: "uses" })}
${arrow(547, 228, 547, 278, { label: "shares" })}
${arrow(792, 290, 654, 192, { label: "compile", bend: [744, 250, 706, 210] })}
${arrow(792, 326, 524, 468, { label: "runtime", bend: [720, 392, 610, 424] })}
${arrow(524, 484, 608, 484, { label: "uses" })}
${arrow(812, 484, 876, 484, { label: "tracks" })}
${codeChip(376, 594, "template/SFC -> compiler -> render -> runtime", 350)}
`,
      }),
  },
  {
    path: "10-minimum-example/package-architecture/runtime-core-dom-overview.svg",
    svg: () =>
      diagram({
        width: 1120,
        height: 640,
        title: "runtime-core and runtime-dom responsibilities",
        subtitle:
          "runtime-core keeps pure rendering logic; runtime-dom injects browser-specific node operations.",
        body: `
${lane(508, 96, 552, 190, "runtime-core")}
${lane(420, 360, 640, 214, "runtime-dom")}
${pill(60, 420, 130, 42, "Developer")}
${box(244, 396, 196, 84, "~/packages/index.ts", { sub: "public entry" })}
${box(536, 172, 188, 70, "createAppAPI", { sub: "factory" })}
${box(816, 172, 188, 70, "createRenderer", { sub: "factory" })}
${box(456, 454, 190, 72, "runtime-dom/index.ts", { sub: "compose APIs", accent: true })}
${box(708, 454, 148, 72, "render", { sub: "from core" })}
${box(900, 454, 126, 72, "nodeOps", { sub: "DOM ops" })}
${arrow(190, 441, 244, 438)}
${arrow(440, 438, 456, 486)}
${arrow(548, 454, 618, 242, { label: "create app" })}
${arrow(760, 454, 888, 242, { label: "create renderer" })}
${arrow(900, 454, 908, 242, { label: "inject options" })}
${arrow(646, 490, 708, 490)}
${arrow(856, 490, 900, 490)}
${codeChip(238, 520, "createApp(App).mount()", 260)}
`,
      }),
  },
  {
    path: "10-minimum-example/package-architecture/renderer-dependency-injection.svg",
    svg: () =>
      diagram({
        width: 980,
        height: 470,
        title: "Renderer dependency injection",
        subtitle:
          "The renderer depends on a contract, then runtime-dom provides the concrete DOM operations.",
        body: `
${box(76, 176, 204, 84, "RendererOptions", { sub: "contract", accent: true })}
${box(398, 132, 230, 78, "createRenderer(options)", { sub: "runtime-core" })}
${box(398, 270, 230, 78, "render", { sub: "pure render logic" })}
${box(748, 176, 176, 84, "nodeOps", { sub: "runtime-dom" })}
${arrow(748, 218, 628, 170, { label: "inject" })}
${arrow(280, 218, 398, 170, { label: "shape" })}
${arrow(512, 210, 512, 270)}
${codeChip(70, 318, "setElementText()", 170)}
${codeChip(748, 318, "document.*", 140)}
${text(490, 408, "DOM APIs stay outside runtime-core.", { className: "muted-label" })}
`,
      }),
  },
  {
    path: "10-minimum-example/package-architecture/create-app-api-factory.svg",
    svg: () =>
      diagram({
        width: 980,
        height: 500,
        title: "createAppAPI factory flow",
        subtitle: "runtime-dom prepares render(), then runtime-core builds createApp() around it.",
        body: `
${box(70, 170, 158, 70, "nodeOps", { sub: "DOM ops" })}
${box(294, 170, 190, 70, "createRenderer", { sub: "returns render" })}
${box(548, 170, 210, 70, "createAppAPI", { sub: "accepts render" })}
${box(804, 170, 126, 70, "createApp", { sub: "public API", accent: true })}
${arrow(228, 205, 294, 205)}
${arrow(484, 205, 548, 205, { label: "render" })}
${arrow(758, 205, 804, 205)}
${box(210, 326, 204, 64, "rootComponent", { sub: "user component" })}
${box(566, 326, 202, 64, "app.mount()", { sub: "selector -> container" })}
${arrow(414, 358, 566, 358, { label: "render message" })}
${arrow(866, 240, 670, 326, { label: "returns app", bend: [866, 286, 770, 296] })}
`,
      }),
  },
  {
    path: "10-minimum-example/reactivity/target-map-structure.svg",
    svg: () =>
      diagram({
        width: 980,
        height: 540,
        title: "targetMap structure",
        subtitle:
          "A WeakMap connects each reactive target to keys, then keys to dependent effects.",
        body: `
${box(60, 210, 170, 88, "targetMap", { sub: "WeakMap<Target, KeyToDepMap>", accent: true })}
${box(328, 130, 150, 70, "state1", { sub: "target" })}
${box(328, 320, 150, 70, "state2", { sub: "target" })}
${box(560, 130, 148, 70, '"name"', { sub: "key" })}
${box(560, 320, 148, 70, '"count"', { sub: "key" })}
${box(790, 130, 140, 70, "Dep", { sub: "updateComponent" })}
${box(790, 320, 140, 70, "Dep", { sub: "onCountUpdated" })}
${arrow(230, 240, 328, 164, { label: "target" })}
${arrow(230, 268, 328, 354, { label: "target" })}
${arrow(478, 165, 560, 165, { label: "key" })}
${arrow(478, 355, 560, 355, { label: "key" })}
${arrow(708, 165, 790, 165, { label: "effect" })}
${arrow(708, 355, 790, 355, { label: "effect" })}
${codeChip(382, 442, "state1.name -> updateComponent", 300)}
${codeChip(382, 486, "state2.count -> onCountUpdated", 320)}
`,
      }),
  },
  {
    path: "10-minimum-example/reactivity/reactive-track-trigger.svg",
    svg: () =>
      diagram({
        width: 1120,
        height: 620,
        title: "reactive(), track(), and trigger()",
        subtitle: "Proxy get registers the active effect; Proxy set finds it and runs it again.",
        body: `
${box(60, 256, 150, 72, "target", { sub: "plain object" })}
${box(278, 256, 150, 72, "reactive()", { sub: "wrap" })}
${box(496, 256, 150, 72, "Proxy", { sub: "get / set", accent: true })}
${arrow(210, 292, 278, 292)}
${arrow(428, 292, 496, 292)}
${box(730, 144, 140, 66, "track()", { sub: "on get" })}
${box(730, 382, 140, 66, "trigger()", { sub: "on set" })}
${box(890, 242, 160, 88, "targetMap", { sub: "deps by target/key", accent: true })}
${box(890, 60, 160, 66, "activeEffect", { sub: "current subscriber" })}
${box(890, 486, 160, 66, "effect.run()", { sub: "fn()" })}
${arrow(646, 270, 730, 177, { label: "get" })}
${arrow(646, 314, 730, 415, { label: "set" })}
${arrow(870, 177, 890, 104, { label: "read" })}
${arrow(870, 177, 890, 264, { label: "register" })}
${arrow(870, 415, 890, 304, { label: "lookup" })}
${arrow(970, 330, 970, 486, { label: "run" })}
${text(352, 494, "The Proxy is the gate where reads and writes become dependency events.", { className: "muted-label" })}
`,
      }),
  },
  {
    path: "10-minimum-example/reactivity/reactivity-setup-flow.svg",
    svg: () =>
      diagram({
        width: 1120,
        height: 720,
        title: "How reactivity is created during mount",
        subtitle: "The first render collects dependencies; later writes use that collected map.",
        body: `
${box(72, 140, 170, 70, "setup()", { sub: "create state" })}
${box(310, 140, 190, 70, "reactive state", { sub: "Proxy" })}
${box(568, 140, 230, 70, "ReactiveEffect", { sub: "updateComponent" })}
${box(864, 140, 180, 70, "effect.run()", { sub: "sets activeEffect", accent: true })}
${arrow(242, 175, 310, 175)}
${arrow(500, 175, 568, 175)}
${arrow(798, 175, 864, 175)}
${box(864, 330, 180, 70, "render()", { sub: "reads state.count" })}
${box(568, 330, 230, 70, "getter", { sub: "track(target, key)" })}
${box(310, 330, 190, 70, "targetMap", { sub: "state.count -> effect", accent: true })}
${arrow(954, 210, 954, 330)}
${arrow(864, 365, 798, 365)}
${arrow(568, 365, 500, 365)}
${box(72, 510, 170, 70, "increment()", { sub: "state.count++" })}
${box(310, 510, 190, 70, "setter", { sub: "trigger(target, key)" })}
${box(568, 510, 230, 70, "find effect", { sub: "from targetMap" })}
${box(864, 510, 180, 70, "updateComponent", { sub: "patch screen", accent: true })}
${arrow(242, 545, 310, 545)}
${arrow(500, 545, 568, 545)}
${arrow(798, 545, 864, 545)}
${arrow(954, 510, 954, 400, { label: "next render", dashed: true })}
`,
      }),
  },
  {
    path: "10-minimum-example/virtual-dom/patch-function-architecture.svg",
    svg: () =>
      diagram({
        width: 980,
        height: 560,
        title: "patch function architecture",
        subtitle: "patch dispatches by VNode type, then splits mount and update work.",
        body: `
${box(390, 118, 200, 72, "patch(n1, n2)", { sub: "entry point", accent: true })}
${box(164, 274, 190, 72, "processText", { sub: "type === Text" })}
${box(626, 274, 190, 72, "processElement", { sub: "element vnode" })}
${arrow(390, 154, 354, 274, { label: "Text" })}
${arrow(590, 154, 626, 274, { label: "Element" })}
${box(70, 422, 150, 60, "mountText", { sub: "n1 == null" })}
${box(278, 422, 150, 60, "patchText", { sub: "update" })}
${box(532, 422, 160, 60, "mountElement", { sub: "n1 == null" })}
${box(754, 422, 160, 60, "patchElement", { sub: "update" })}
${arrow(220, 346, 145, 422)}
${arrow(298, 346, 353, 422)}
${arrow(690, 346, 612, 422)}
${arrow(770, 346, 834, 422)}
`,
      }),
  },
  {
    path: "10-minimum-example/minimum-component/component-instance-flow.svg",
    svg: () =>
      diagram({
        width: 1040,
        height: 560,
        title: "Component instance flow",
        subtitle:
          "The renderer creates an instance so each component can keep its own render state.",
        body: `
${box(62, 170, 190, 72, "h(MyComponent)", { sub: "component VNode" })}
${box(322, 170, 214, 72, "processComponent", { sub: "mount or update" })}
${box(616, 170, 220, 72, "create instance", { sub: "ComponentInternalInstance", accent: true })}
${arrow(252, 206, 322, 206)}
${arrow(536, 206, 616, 206)}
${box(180, 360, 164, 64, "setup()", { sub: "returns render" })}
${box(438, 360, 164, 64, "subTree", { sub: "render result" })}
${box(696, 360, 164, 64, "patch()", { sub: "DOM update" })}
${arrow(726, 242, 262, 360, { label: "initialize", bend: [700, 300, 420, 300] })}
${arrow(344, 392, 438, 392)}
${arrow(602, 392, 696, 392)}
${codeChip(392, 476, "instance.subTree / instance.update / instance.effect", 360)}
`,
      }),
  },
  {
    path: "20-basic-virtual-dom/patch-keyed-children/same-length-index-patch.svg",
    svg: () =>
      keyedChildrenDiagram({
        title: "Index-based patch with equal lengths",
        subtitle:
          "The first implementation works only when old and new child arrays line up by index.",
        oldItems: ["li 1", "li 2", "li 3", "li 4"],
        newItems: ["li 1", "li 2", "li 3", "li 4"],
        links: [
          [0, 0, "patch", false],
          [1, 1, "patch", false],
          [2, 2, "patch", false],
          [3, 3, "patch", false],
        ],
      }),
  },
  {
    path: "20-basic-virtual-dom/patch-keyed-children/deleted-child-bug.svg",
    svg: () =>
      keyedChildrenDiagram({
        title: "Deleted child bug",
        subtitle: "Looping over c2 leaves extra old nodes untouched.",
        oldItems: ["li a", "li b", "li c", "li d"],
        newItems: ["li e", "li f", "li g"],
        links: [
          [0, 0, "patch", false],
          [1, 1, "patch", false],
          [2, 2, "patch", false],
        ],
        notes: ["li d is never visited", "The DOM keeps a stale child."],
      }),
  },
  {
    path: "20-basic-virtual-dom/patch-keyed-children/inserted-child-index-bug.svg",
    svg: () =>
      keyedChildrenDiagram({
        title: "Inserted child with index matching",
        subtitle: "A new item shifts positions, so index-based comparison pairs the wrong nodes.",
        oldItems: ["li 1", "li 2", "li 3", "li 4"],
        newItems: ["li 1", "new li", "li 2", "li 3", "li 4"],
        links: [
          [0, 0, "patch", false],
          [1, 1, "wrong", true],
          [2, 2, "wrong", true],
          [3, 3, "wrong", true],
        ],
        notes: [
          "The inserted node changes every later index.",
          "Keys are needed to find identity.",
        ],
      }),
  },
  {
    path: "20-basic-virtual-dom/patch-keyed-children/inserted-child-keyed-match.svg",
    svg: () =>
      keyedChildrenDiagram({
        title: "Inserted child with keyed matching",
        subtitle: "Keys let the renderer match old and new nodes by identity instead of position.",
        oldItems: ["li 1", "li 2", "li 3", "li 4"],
        newItems: ["li 1", "new li", "li 2", "li 3", "li 4"],
        links: [
          [0, 0, "key", false],
          [1, 2, "key", false],
          [2, 3, "key", false],
          [3, 4, "key", false],
        ],
        notes: ["new li is mounted", "Existing nodes keep their identity."],
      }),
  },
  {
    path: "20-basic-virtual-dom/bit-flags/shape-flag-overview.svg",
    svg: () =>
      diagram({
        width: 980,
        height: 500,
        title: "ShapeFlags pack VNode shape into bits",
        subtitle: "A renderer can check one number instead of repeating type checks.",
        body: `
${box(78, 158, 210, 82, "VNode", { sub: "type: 'div'\nchildren: []", accent: true })}
${box(388, 126, 210, 58, "ELEMENT", { sub: "1" })}
${box(388, 212, 210, 58, "ARRAY_CHILDREN", { sub: "1 << 4" })}
${box(692, 158, 210, 82, "shapeFlag", { sub: "0b0001_0001", accent: true })}
${arrow(288, 198, 388, 155)}
${arrow(288, 198, 388, 241)}
${arrow(598, 155, 692, 198)}
${arrow(598, 241, 692, 198)}
${codeChip(326, 344, "vnode.shapeFlag & ShapeFlags.ELEMENT", 350)}
${codeChip(326, 394, "vnode.shapeFlag & ShapeFlags.ARRAY_CHILDREN", 390)}
`,
      }),
  },
  {
    path: "30-basic-reactivity-system/reactivity-optimization/push-pull-overview.svg",
    svg: () =>
      diagram({
        width: 1040,
        height: 520,
        title: "Push-Pull reactivity overview",
        subtitle: "Changes push dirty marks; reads pull the recalculation only when it is needed.",
        body: `
${box(74, 170, 172, 70, "signal changes", { sub: "trigger" })}
${box(322, 170, 180, 70, "push phase", { sub: "mark dirty", accent: true })}
${box(578, 170, 180, 70, "computed read", { sub: "getter" })}
${box(834, 170, 150, 70, "pull phase", { sub: "recalculate if dirty", accent: true })}
${arrow(246, 205, 322, 205)}
${arrow(502, 205, 578, 205)}
${arrow(758, 205, 834, 205)}
${box(176, 340, 236, 70, "version check", { sub: "globalVersion / dep.version" })}
${box(620, 340, 236, 70, "linked deps", { sub: "Dep <-> Subscriber" })}
${arrow(412, 375, 620, 375, { label: "O(1) updates", dashed: true })}
${text(520, 462, "The actual work is delayed until a value is read again.", { className: "muted-label" })}
`,
      }),
  },
  {
    path: "50-basic-template-compiler/transform/basic-compiler-pipeline.svg",
    svg: () =>
      diagram({
        width: 1040,
        height: 430,
        title: "Minimum compiler pipeline",
        subtitle:
          "The early implementation parses the template and immediately generates a render function.",
        body: `
${box(66, 178, 190, 70, "source", { sub: "template string" })}
${box(318, 178, 160, 70, "Parser", { sub: "baseParse" })}
${box(540, 178, 160, 70, "AST", { sub: "template AST", accent: true })}
${box(762, 178, 190, 70, "Codegen", { sub: "render function" })}
${arrow(256, 213, 318, 213)}
${arrow(478, 213, 540, 213)}
${arrow(700, 213, 762, 213)}
`,
      }),
  },
  {
    path: "50-basic-template-compiler/transform/compiler-pipeline-with-transformer.svg",
    svg: () =>
      diagram({
        width: 1120,
        height: 450,
        title: "Compiler pipeline with transformer",
        subtitle: "transform() prepares codegen-oriented nodes before the code generator runs.",
        body: `
${box(58, 188, 170, 70, "source", { sub: "template" })}
${box(282, 188, 150, 70, "Parser", { sub: "baseParse" })}
${box(486, 188, 150, 70, "Template AST", { sub: "input focused" })}
${box(690, 188, 160, 70, "Transformer", { sub: "transform()", accent: true })}
${box(904, 188, 160, 70, "Codegen", { sub: "render()" })}
${arrow(228, 223, 282, 223)}
${arrow(432, 223, 486, 223)}
${arrow(636, 223, 690, 223)}
${arrow(850, 223, 904, 223)}
${box(628, 326, 284, 54, "codegenNode / JS AST", { sub: "output focused", muted: true })}
${arrow(770, 258, 770, 326, { dashed: true })}
`,
      }),
  },
  {
    path: "50-basic-template-compiler/transform/transform-type-relationships.svg",
    svg: () =>
      diagram({
        width: 1120,
        height: 620,
        title: "Transform function types",
        subtitle:
          "NodeTransform and DirectiveTransform are function contracts with concrete transform implementations.",
        body: `
${lane(64, 116, 992, 214, "Node transforms")}
${lane(64, 374, 992, 154, "Directive transforms")}
${box(116, 184, 220, 72, "NodeTransform", { sub: "node -> onExit?", accent: true })}
${box(470, 146, 190, 58, "transformElement", { sub: "ElementNode" })}
${box(470, 232, 190, 58, "transformExpression", { sub: "ExpressionNode" })}
${box(770, 188, 190, 58, "other node transforms", { sub: "implementation set" })}
${arrow(336, 210, 470, 175, { label: "implements" })}
${arrow(336, 226, 470, 261, { label: "implements" })}
${arrow(660, 175, 770, 208, { label: "and" })}
${box(116, 416, 220, 72, "DirectiveTransform", { sub: "directive -> props", accent: true })}
${box(470, 398, 150, 58, "transformOn", { sub: "v-on" })}
${box(664, 398, 150, 58, "transformFor", { sub: "v-for" })}
${box(858, 398, 150, 58, "transformIf", { sub: "v-if" })}
${box(664, 484, 230, 58, "other directive transforms", { sub: "implementation set" })}
${arrow(336, 442, 470, 427, { label: "implements" })}
${arrow(620, 427, 664, 427)}
${arrow(814, 427, 858, 427)}
${arrow(336, 462, 664, 513, { label: "and", bend: [440, 520, 560, 520] })}
${codeChip(382, 566, "compiler-core/src/transforms", 356)}
`,
      }),
  },
  {
    path: "50-basic-template-compiler/v-bind/directive-node-shape.svg",
    svg: () =>
      diagram({
        width: 760,
        height: 360,
        title: "DirectiveNode shape for v-bind",
        subtitle: "v-bind needs both the argument and the expression as nodes.",
        body: `
${box(72, 146, 180, 70, "DirectiveNode", { sub: "name: bind", accent: true })}
${box(334, 90, 150, 58, "name", { sub: "bind" })}
${box(334, 178, 150, 58, "arg", { sub: "id / [key]" })}
${box(334, 266, 150, 58, "exp", { sub: "count" })}
${box(560, 178, 140, 58, "ExpressionNode", { sub: "isStatic?" })}
${arrow(252, 178, 334, 119)}
${arrow(252, 182, 334, 207)}
${arrow(252, 186, 334, 295)}
${arrow(484, 207, 560, 207)}
`,
      }),
  },
  {
    path: "50-basic-template-compiler/v-bind/transform-vbind-flow.svg",
    svg: () =>
      diagram({
        width: 1080,
        height: 700,
        title: "v-bind transform flow",
        subtitle:
          "The transformer chooses the right codegen path from the argument and binding kind.",
        body: `
${box(430, 104, 220, 64, "DirectiveNode", { sub: "v-bind / :arg", accent: true })}
${box(430, 226, 220, 64, "Has arg?", { sub: "arg exists?" })}
${arrow(540, 168, 540, 226)}
${box(108, 348, 218, 64, "No arg", { sub: 'v-bind="obj"' })}
${box(430, 348, 220, 64, "Static arg", { sub: ":class / :style / :id" })}
${box(754, 348, 218, 64, "Dynamic arg", { sub: ":[key]" })}
${arrow(430, 258, 326, 348, { label: "no" })}
${arrow(540, 290, 540, 348, { label: "yes" })}
${arrow(650, 258, 754, 348, { label: "dynamic" })}
${box(108, 500, 218, 64, "mergeProps()", { sub: "object binding", accent: true })}
${box(430, 500, 220, 64, "normalizeClass/Style", { sub: "if class or style", accent: true })}
${box(754, 500, 218, 64, "normalizeProps()", { sub: "unknown key", accent: true })}
${arrow(217, 412, 217, 500)}
${arrow(540, 412, 540, 500)}
${arrow(863, 412, 863, 500)}
${text(540, 638, "Result: a Codegen property or helper call used by h(...).", { className: "muted-label" })}
`,
      }),
  },
  {
    path: "50-basic-template-compiler/event-modifier/compiler-architecture-core-only.svg",
    svg: () =>
      diagram({
        width: 960,
        height: 560,
        title: "Compiler architecture before DOM modifiers",
        subtitle:
          "The v-on transform still lives in compiler-core, so it must stay DOM independent.",
        body: `
${lane(80, 124, 800, 160, "compiler-core")}
${box(132, 190, 150, 58, "parse", { sub: "template AST" })}
${box(398, 190, 170, 58, "transformOn", { sub: "@click -> onClick", accent: true })}
${box(688, 190, 140, 58, "generate", { sub: "code" })}
${arrow(282, 219, 398, 219)}
${arrow(568, 219, 688, 219)}
${lane(80, 348, 800, 116, "compiler-dom")}
${box(338, 386, 284, 54, "uses compiler-core defaults", { sub: "no DOM-specific transform yet" })}
${arrow(480, 348, 480, 284, { label: "delegates", dashed: true })}
`,
      }),
  },
  {
    path: "50-basic-template-compiler/event-modifier/compiler-architecture-dom-augmentor.svg",
    svg: () =>
      diagram({
        width: 980,
        height: 600,
        title: "Compiler architecture with DOM augmentor",
        subtitle: "compiler-dom wraps core transforms and injects DOM-specific modifier handling.",
        body: `
${lane(86, 108, 808, 170, "compiler-core")}
${box(134, 178, 170, 58, "baseTransformOn", { sub: "DOM free" })}
${box(430, 178, 164, 58, "augmentor", { sub: "callback slot", accent: true })}
${box(724, 178, 122, 58, "result", { sub: "props" })}
${arrow(304, 207, 430, 207)}
${arrow(594, 207, 724, 207)}
${lane(86, 352, 808, 154, "compiler-dom")}
${box(156, 404, 218, 58, "transformOn", { sub: "wrap core" })}
${box(534, 404, 232, 58, "withModifiers()", { sub: "prevent / stop", accent: true })}
${arrow(374, 433, 534, 433, { label: "DOM logic" })}
${arrow(650, 404, 512, 236, { label: "inject augmentor", bend: [650, 320, 560, 300] })}
${text(490, 552, "compiler-core stays portable; compiler-dom owns browser event behavior.", { className: "muted-label" })}
`,
      }),
  },
  {
    path: "50-basic-template-compiler/v-for/for-parse-result.svg",
    svg: () =>
      diagram({
        width: 760,
        height: 380,
        title: "ForParseResult shape",
        subtitle: "v-for decomposes the expression into source, value, key, and index.",
        body: `
${codeChip(168, 106, 'v-for="(fruit, i) in fruits"', 424)}
${box(76, 212, 138, 58, "source", { sub: "fruits", accent: true })}
${box(244, 212, 138, 58, "value", { sub: "fruit" })}
${box(412, 212, 138, 58, "key", { sub: "i" })}
${box(580, 212, 138, 58, "index", { sub: "undefined" })}
${arrow(380, 142, 145, 212)}
${arrow(380, 142, 313, 212)}
${arrow(380, 142, 481, 212)}
${arrow(380, 142, 649, 212)}
`,
      }),
  },
];

for (const item of diagrams) {
  const file = join(outRoot, item.path);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, item.svg(), "utf8");
  console.log(`generated ${file}`);
}
